name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if AZURE_CREDENTIALS is available
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS is NOT set"
            exit 1
          else
            echo "AZURE_CREDENTIALS is set"
          fi

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI command (example)
        run: az account show

      # Step 3: Install dependencies and build the application
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Ensure this generates the `dist` folder

      # Step 4: Deploy the `dist` folder to Azure Web App next test
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: insurancePortal  # Replace with your Azure Web App name
          slot-name: production         # Optional: Specify the deployment slot (default is production)
          package: ./dist  # Replace with the path to your build output (e.g., ./build or a .zip file)       